## for 반복문에서 in 연산자
for 문에 범위 연산자인 in을 사용하면 오른쪽에 명시한 컬렉션 타입의 데이터 개수만큼 반복해서 실행한다.
```
# in 연산자로 간소화한 반복문

main(){
    var list = [10, 20, 30];
    for(var x in list){
        print(x);
    }
}
```

## switch ~ case 선택문
조건에 따라 실행 흐름을 분기할 때 사용한다. 다트에서는 switch의 조건을 정수나 문자열 타입으로 지정할 수 있다. case가 여러개라면 맨 마지막 case문을 제외하고는 break, continue, return, throw 중 하나를 작성해 주어야 한다.
- break : switch문 나가기
- continue : 특정 위치로 이동하기
- return : switch 문이 작성된 함수 종료하기(반환하기)
- throw : switch 문이 작성된 함수 종료하기(던지기)

```
# switch ~ case 문 잘못 사용 예

some(arg){
    switch(arg){
        case 'A':
            print('A');     # 실행 흐름을 지정하지 않아서 오류
        case 'B':
            print('B');
    }
}
```
print('A'); 다음에 break, continue, return, throw 등을 넣어주어야 정상적으로 작동한다.

## 예외 던지기
특정 시점에 예외를 발생시키고 싶으면 throw 문을 이용한다.
```
# 예외 던지기

some(){
    throw Exception('my exception');
}
```
Exception 클래스 이외의 다른 객체를 던져도 된다.
```
# 문자열 던지기

some(){
    throw 'my exception';
}
```

```
# 사용자 정의 객체 던지기

class User{}
some(){
    throw User();
}
```

## 예외 처리
try~on~finally 구문은 예외 처리 조합이다. try 문에 작성한 코드에서 예외가 발생하면 on 문이 실행되며, finally 문에는 예외와 상관없이 무조건 실행할 코드를 작성한다.
```
# try~on~finally 예외 처리

some(){
    throw FormatException('my exception');
}
main(List<String> args){
    try{
        print('step1....');
        some();
        print('step2....');
    }on FormatException{
        print('step3....');
    }on Exception{
        print('step4....');
    }finally{
        print('step5....');
    }
    print('step6....');
}

출력 -> step1....
       step3....
       step5....
       step6....
```
try 문에서 some() 함수가 실행되어 FormatException을 던지기 때문에 on FormatException{} 구문이 실행된다.  
예외 처리문에서 어떤 예외가 발생했는지 알고 싶다면 catch 문으로 예외 객체를 받을 수 있다. on FormatException catch(e) 라고 작성하면 발생한 예외 객체가 e에 전달된다.
```
# catch를 사용해서 예외 객체 가져오기

some(){
    throw FormatException('my exception');
}
main(List<String> args){
    try{
        print('step1....');
        some();
        print('step2....');
    }on FormatException catch(e){
        print('step3....$e');
    }on Exception catch(e){
        print('step4....$e');
    }finally{
        print('step5....');
    }
    print('step6....');
}

출력 -> step1....
       step3....FormatException: my exception
       step5....
       step6....
```

예외 종류를 구분하지 않는다면 간단하게도 작성 가능하다.
```
# try~catch 예외 처리

try{
    some();
}catch(e){
    print('catch....$e');
}
```